CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    post_id INTEGER NOT NULL,
    path VARCHAR NOT NULL,
    description TEXT,
    tag VARCHAR,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);